import { StyleSheet } from "react-native";import { DarkBlue, LightGrayColor, black11, blueTypeTextColor, grayOuterLine as grayBorderLine, grayD9, grayE8, grayEC, grayOuterLine, secondaryTextColor, white } from "../../../theme/Colors";
import Fonts from "../../../assets/Fonts";


export const styles  = StyleSheet.create({
    container:{ 
        backgroundColor:white,
        flex:1,
    },
    firstRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginVertical:10,
        alignItems:'center',
        marginHorizontal:20,
        paddingTop:5

    },
    dividerLine:{
        backgroundColor:grayE8,
        height:1,
        width:'100%',
        marginVertical:10
    },
    examNViewAllText:{
        fontFamily:Fonts.POPPINS_SEMIBOLD,
        fontSize:16,
        color:blueTypeTextColor
    },
    
    leftGroupText:{
        fontFamily:Fonts.POPPINS_SEMIBOLD,
        fontSize:13,
        color:secondaryTextColor,
        marginHorizontal:20,
        marginVertical:20
    },
    groupsBgImage:{
        height:80,
        width:105,
        justifyContent:'center',
        marginLeft:20,
        borderRadius:4,
        overflow:'hidden'

    },
    createPostContainer:{
        flexDirection:'row',
        marginHorizontal:20,
        justifyContent:'space-between',
        marginTop:5,
        marginBottom:15
    },
    
    addPostIcon:{
        height:22,
        width:22,
        alignSelf:'center',
        marginRight:10
    },
    searchIcon:{
        height:21,
        width:21,
        alignSelf:'center'
    },
    searchContainer:{
        borderLeftWidth:1,
        paddingLeft:10,
        justifyContent:'center',
        borderLeftColor:grayOuterLine,
    },
    postContainer:{
        borderBottomColor:grayEC,
        borderBottomWidth:8,
        paddingHorizontal:20,
        backgroundColor:white
    },
    fatDivider:{
        backgroundColor:grayEC,
        height:8,
        marginVertical:7
    },
    rowSpaceBetween:{
        flexDirection:'row',
        justifyContent:"space-between"
    },
    recentText:{
        fontFamily:Fonts.POPPINS_MEDIUM,
        fontSize:14,
        color:secondaryTextColor,
        marginVertical:14
    },
    text13light:{
        fontFamily:Fonts.POPPINS_LIGHT,
        fontSize:13,
        color:secondaryTextColor,
    },
    text13medium:{
        fontFamily:Fonts.POPPINS_MEDIUM,
        fontSize:13,
        color:LightGrayColor,
    },
    text13semi:{
        fontFamily:Fonts.POPPINS_SEMIBOLD,
        fontSize:13,
        color:LightGrayColor,
        alignSelf:'center'
    },
    text18semi:{
        fontFamily:Fonts.POPPINS_SEMIBOLD,
        fontSize:18,
        color:black11,
    },
    filterContainer:{
        alignSelf:'center',
        flexDirection:'row'
    },
    filterIcon:{
        height:15,
        width:19,
        alignSelf:'center',
        marginRight:10
    },
    profileContainer:{
        flexDirection:'row'
    },

    profiPicBig:{
        height:37,
        width:37,
        borderRadius:50,
        alignSelf:'center',
        backgroundColor:grayE8,
        marginRight:15
    },
    threeDots:{
        width:3.6,
        height:16,
        alignSelf:'center'
    },
    reactionRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:15,
    },
    grayDivider:{
        backgroundColor:grayBorderLine,
        height:1,
        marginTop:15
    },
    verticalLine:{
        backgroundColor:grayOuterLine,
        height:31,
        width:1
      },
    likeIcon:{
        height:16,
        width:17,
        alignSelf:'center',
        marginRight:5
    },
    commentIcon:{
        height:10,
        width:16,
        alignSelf:'center',
        marginRight:5
    },
    eyeIcon:{
        height:16,
        width:17,
        alignSelf:'center',
        marginRight:5
    },
    smallProfilePic:{
        height:19,
        width:19,
        alignSelf:'center',
        backgroundColor:grayE8,
        borderRadius:50,
        marginRight:5
    },
    text14popMedium:{
        fontFamily:Fonts.POPPINS_MEDIUM,
        fontSize:14,
        color:LightGrayColor,
        alignSelf:'center',
        marginRight:5
    },
    likeCommentRow:{
        justifyContent:'space-between'

    }

    
})